### ISSUE TITLE
SPARQList（本番用）のインストール

### ISSUE THREAD

**Issue by mitsuhashi** [dbcls/togoid-config#45]
#### 作業環境等
- 動作確認用URL:  https://test64.biosciencedbc.jp/togosite/sparqlist/
- インストール場所
    - smp05:/ssd/togosite/sparqlist
    - 動作ユーザ：mitsuhashi (dockerグループに所属)
    - docker-compose.ymlの内容：PORT番号($SPARQLIST_PORT=11001)
```
[mitsuhashi@smp05 sparqlist]$ cat docker-compose.yml
version: '3.5'

services:
  sparqlist:
    build: ./sparqlist
    env_file: togosite.env
    volumes:
      - ./repository:/app/repository
    ports:
      - ${SPARQLIST_PORT:-80}:3000
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
[mitsuhashi@smp05 sparqlist]$ cat togosite.env
ADMIN_PASSWORD=<<slackで共有>>
[mitsuhashi@smp05 sparqlist]$ cat .env
SPARQLIST_PORT=11001
[mitsuhashi@smp05 sparqlist]$
```

#### インストール手順
記入予定

#### TODO
- リバースプロキシ(https://integbio.jp/togosite/sparqlist)からの転送設定
- マークダウンファイルのバックアップ
-  実行ユーザの変更?(mitsuhashi->togosite?)
